//@version=3
// VERSION INICIAL REQUIERE CONFIGURAR LOS PARAMETROS
study(title="RSI, Estocastico e MACD", shorttitle="RSI, Estocastico e MACD")
//MACD
fast_length = input(title="Fast Length", type=integer, defval=12)
slow_length = input(title="Slow Length", type=integer, defval=26)
src = input(title="Source", type=source, defval=close)
signal_length = input(title="Signal Smoothing", type=integer, minval = 1, maxval = 50, defval = 9)
sma_source = input(title="Simple MA(Oscillator)", type=bool, defval=false)
sma_signal = input(title="Simple MA(Signal Line)", type=bool, defval=false)

// Plot colors
col_grow_above = #26A69A
col_grow_below = #FFCDD2
col_fall_above = #B2DFDB
col_fall_below = #EF5350
col_macd = #0094ff
col_signal = #ff6a00

// Calculating
fast_ma = sma_source ? sma(src, fast_length) : ema(src, fast_length)
slow_ma = sma_source ? sma(src, slow_length) : ema(src, slow_length)
macd = fast_ma - slow_ma
signal = sma_signal ? sma(macd, signal_length) : ema(macd, signal_length)
hist = macd - signal

plot(hist, title="Histogram", style=columns, color=(hist>=0 ? (hist[1] < hist ? col_grow_above : col_fall_above) : (hist[1] < hist ? col_grow_below : col_fall_below) ), transp=0 )
plot(macd, title="MACD", color=col_macd, transp=0)
plot(signal, title="Signal", color=col_signal, transp=0)

//RSI(14,close)
len = input(14, minval=1, title="RSI - Longitud")
up = rma(max(change(close), 0), len)
down = rma(-min(change(close), 0), len)
rsi = down == 0 ? 120 : up == 0 ? 0 : 120 - (120 / (1 + up / down))
plot(rsi + 160, color=orange, title="RSI")
band270 = hline(245, title="RSI - Banda superior")
band230 = hline(200, title="RSI - Banda inferior")
fill(band270, band230, color=gray, transp=75, title="RSI - Fundo")

//STOCH(14,3,3)
length = input(14, minval=1, title="STOCH - K")
smoothK = input(3, minval=1, title="STOCH - D")
smoothD = input(3, minval=1, title="STOCH - Smooth")
k = sma(stoch(close, high, low, length), smoothK)
d = sma(k, smoothD)
plot(k + 60, color=blue, title="STOCH - K")
plot(d + 60, color=orange, title="STOCH - D")
band180 = hline(140, title="STOCH - Banda superior")
band120 = hline(80, title="STOCH - Banda superior")
band100 = hline(110,  color=gray, editable=false, linestyle=solid)
fill(band180, band120, color=gray, transp=75, title="STOCH - Fundo")